name: rnaseq_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - hisat2
  - samtools
  - fastp
  - subread
  - r-base>=4.2
  - r-tidyverse
  - r-pheatmap
  - r-rcolorbrewer
  - r-ggplot2
  - bioconductor-deseq2
  - bioconductor-enhancedvolcano
  - bioconductor-clusterprofiler
  - bioconductor-annotationdbi
  - bioconductor-enrichplot
  - bioconductor-msigdbr
  - bioconductor-org.hs.eg.db
  - bioconductor-org.eck12.eg.db
  - bioconductor-org.at.tair.db
